package com.tugasakhir;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.graphwalker.core.machine.ExecutionContext;
import org.graphwalker.java.annotation.AfterExecution;
import org.graphwalker.java.annotation.BeforeExecution;

import org.graphwalker.java.annotation.GraphWalker;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;

/**
 * Implements the GraphWalker model: src/main/resources/SmallTest.json
 * <p/>
 * The interface SmallTest, that SomeSmallTest implements, is generated by
 * running: mvn graphwalker:generate-sources
 * also: mvn compile
 */
@GraphWalker(value = "random(edge_coverage(100))", start = "v_Home")
public class Test extends ExecutionContext implements Home {

  private AndroidDriver<MobileElement> driver;

  @Override
  public void v_Home() {
    MobileElement button_email = this.driver.findElementById("com.telkom.tracencare:id/tab_email");
    button_email.click();
    // this.driver.wait(10000, 50);
    System.out.println("Running: v_NewVertex");
  }

  // @Override
  // public void v_Login() {

  // MobileElement button_email =
  // this.driver.findElementById("com.telkom.tracencare:id/tab_email");
  // button_email.click();
  // MobileElement textField_email =
  // this.driver.findElementById("com.telkom.tracencare:id/et_email_auth");
  // textField_email.click();
  // textField_email.sendKeys("maulidito@gmail.com");
  // // textField_email.setValue("maulidito@gmail.com");
  // MobileElement button_login =
  // this.driver.findElementById("com.telkom.tracencare:id/btn_login");
  // button_login.click();
  // // this.driver.wait(500);

  // System.out.println("Running: v_NewVertex");
  // }

  // @Override
  // public void e_ClickIndonesiaCitizen() {
  // MobileElement button_wni =
  // this.driver.findElementById("com.telkom.tracencare:id/btn_wni");
  // button_wni.click();
  // MobileElement button_Privacy =
  // this.driver.findElementById("com.telkom.tracencare:id/cb_tnc");
  // button_Privacy.click();
  // MobileElement button_Agree =
  // this.driver.findElementById("com.telkom.tracencare:id/btn_agree_tou");
  // button_Agree.click();
  // System.out.println("Running: e_SomeOtherAction");
  // }

  @Override
  public void v_Vaccine() {
    // TODO Auto-generated method stub

  }

  @Override
  public void v_Covid19TestResult() {
    // TODO Auto-generated method stub

  }

  @Override
  public void v_eHAC() {
    // TODO Auto-generated method stub

  }

  @Override
  public void v_TravelRegulations() {
    // TODO Auto-generated method stub

  }

  @Override
  public void v_Telemedicine() {
    // TODO Auto-generated method stub

  }

  @Override
  public void v_HealthcareFacility() {
    // TODO Auto-generated method stub

  }

  @Override
  public void v_Covid19Statistic() {
    // TODO Auto-generated method stub

  }

  @Override
  public void v_FindHospital() {
    // TODO Auto-generated method stub

  }

  @Override
  public void v_ScanQRCode() {
    // TODO Auto-generated method stub

  }

  @Override
  public void v_Notification() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Click_Vaccine() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Click_Covid19TestResult() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Click_eHAC() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Click_TravelRegulations() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Click_Telemedicine() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Click_HealthcareFacility() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Click_Covid19Statistic() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Click_FindHospital() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Click_ScanQRCode() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Click_Notifications() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Back_FindHospital() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Back_Covid19Statistic() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Back_HealthcareFacility() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Back_Telemedicine() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Back_TravelRegulations() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Back_eHAC() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Back_Covid19TestResult() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Back_Vaccine() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Back_Notifications() {
    // TODO Auto-generated method stub

  }

  @Override
  public void e_Back_ScanQRCode() {
    // TODO Auto-generated method stub

  }

  public class configurationDevice {
    // Locations
    // lat -6.402484
    // lang 106.794243

    // gennymotion
    String deviceName = "emulator_device";
    String deviceVersion = "8.1";
    String udid = "192.168.43.107:5555";

    // avd
    // String deviceName = "Pixel_API_26";
    // String deviceVersion = "8.0";
  }

  private class appConfiguration {
    final String appPackage = "com.telkom.tracencare";
    final String activity = "com.telkom.tracencare.ui.MainActivity";
  }

  @BeforeExecution
  public void setup() {
    configurationDevice device = new configurationDevice();
    appConfiguration appConf = new appConfiguration();
    File classpathRoot = new File(System.getProperty("user.dir"));
    File appDir = new File(classpathRoot, "src/main/apk");
    File app = new File(appDir, "peduliLindungi.apk");
    DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, device.deviceName);
    capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, device.deviceVersion);
    capabilities.setCapability(MobileCapabilityType.UDID, device.udid);
    // capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "Appium");
    capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");

    // capabilities.setCapability("app", app.getAbsolutePath());
    capabilities.setCapability("appPackage", appConf.appPackage);
    capabilities.setCapability("appActivity", appConf.activity);
    capabilities.setCapability("avdArgs", "netfast");
    capabilities.setCapability("noReset", "true");
    // capabilities.setCapability("autoWebview", "true");
    capabilities.setCapability("autoLaunch", "false");
    capabilities.setCapability("fullReset", "false");

    try {
      System.out.println("get ready for init driver");
      driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

      driver.launchApp();
      System.out.println("Check driver =>" + driver);
    } catch (MalformedURLException e) {
      System.out.println("error in driver section");
      e.printStackTrace();
    } catch (Exception e) {
      System.out.println("error in driver section Execption => " + e.toString());
    }
    this.driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
  }

  @AfterExecution
  public void tearDown() {
    driver.quit();
    System.out.println("TEST DONE");
  }

}
